main: tld.floliroy.plugin.FloPlugin
name: FloPlugin
version: 1.0
author: Floliroy
description: My first plugin
commands:
    mycommand:
       description: An example command
       usage: /mycommand
    diamond:
       description: Give a diamond
       usage: /diamond